# Generated by Django 5.2.6 on 2025-09-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="selected_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_working_on",
                to="event.problemstatement",
            ),
        ),
    ]
