# Generated by Django 5.2.6 on 2025-09-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_team_selected_problem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="highlight",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="technical_skills",
        ),
        migrations.AddField(
            model_name="submission",
            name="ideation_text",
            field=models.TextField(
                blank=True, help_text="The core idea for the project.", null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="plan_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF of the implementation plan.",
                null=True,
                upload_to="plans/",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="project_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="team",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="event.team"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("removed", "Removed"),
                ],
                default="accepted",
                max_length=10,
            ),
        ),
    ]
